name: CI | CD Calculator 📦🚀

on:
  push:
    branches:
     - "master"
  workflow_dispatch:

env:
  image_name: ${{ secrets.DOCKERHUB_USERNAME }}/calculator:1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.image_name }}
  
  deploy:
    environment:
      name: production
      url: 's3://patch'
    name: Deploy-S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Checkout
        run: mkdir app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull image
        run: docker pull ${{ env.image_name }}
      
      - name: Deploy container
        run:  docker run -p 8080:3000 -itd --name=calculator ${{ env.image_name }}
      
      - name: Extract build from container
        run: sudo docker cp calculator:/app/build /app
      
      - name: validate
        run: ls -lha
  